removed global components and added them locally, added resp to exist…
whynotearth/golf-app pull request #3
Opened 2020-11-19 07:56 UTC by freedannyv

…ing views

2020-11-19 08:41 UTC, giteshk11 requested changes
@freedannyv Left some feedback for you

2020-11-19 08:41 UTC, giteshk11 commented on src/components/NavMenu.vue
> +img {
don't use style with img tag
make a parent div and give it width and height and try avoiding making your own classes

2020-11-19 08:41 UTC, giteshk11 commented on src/components/InputName.vue
> +  </div>
You can further break this code into its own component so that we can reuse it later

2020-11-19 08:41 UTC, giteshk11 commented on src/components/InputName.vue
> +</style>
avoid creating own styles

2020-11-19 08:41 UTC, giteshk11 commented on src/components/utilities/BaseButton.vue
> +    @click="$emit('clicked')"
why is there a click event, router link only supports `to`

2020-11-19 08:41 UTC, giteshk11 commented on src/components/utilities/BaseButton.vue
> +}
Please tailwind for these, there's no point of using tailwind if we are creating our own classes

2020-11-19 08:41 UTC, giteshk11 commented on src/components/utilities/BaseButton.vue
> +</style>
Same here, use tailwind

2020-11-19 08:49 UTC, freedannyv commented on src/components/NavMenu.vue
> +img {
updated

2020-11-19 08:49 UTC, freedannyv commented on src/components/utilities/BaseButton.vue
> +    @click="$emit('clicked')"
good question. updated 👍🏻

2020-11-19 09:19 UTC, freedannyv commented on src/components/InputName.vue
> +</style>
got it

2020-11-19 09:58 UTC, freedannyv commented on src/components/utilities/BaseButton.vue
> +}
added these into the tailwind.css file as their own classes

2020-11-21 11:56 UTC, giteshk11 requested changes

2020-11-23 05:18 UTC, closed without merging

2020-11-23 05:19 UTC, giteshk11 commented
Already merged with staging