updated basecard, added bgs and styling
whynotearth/golf-app pull request #7
Opened 2020-11-23 07:23 UTC by freedannyv

2020-11-23 08:27 UTC, giteshk11 commented on src/views/GameScores.vue
>            />
I think its better if restrict the score to double digits
Right now user input N digits number

2020-11-23 08:39 UTC, giteshk11 requested changes
Left some feedback comments

2020-11-23 08:39 UTC, giteshk11 commented on src/components/utilities/BaseCard.vue
> +</style>
This whole component just has 3 lines of code, which could be just written directly without using this component.
Please find an alternative way

2020-11-23 08:39 UTC, giteshk11 commented on src/styles/tailwind.css
> +  @apply py-2 px-8 uppercase rounded-full shadow-lg bg-ff6350 text-base;
You can place this class in the component's CSS style

2020-11-23 08:39 UTC, giteshk11 commented on src/styles/tailwind.css
>  .back {
Same for this

2020-11-23 14:20 UTC, merged

2020-11-24 02:19 UTC, freedannyv commented on src/views/GameScores.vue
>            />
I'm not entirely sure on how to do this

2020-11-24 02:31 UTC, freedannyv commented on src/components/utilities/BaseCard.vue
> +</style>
I made a class in the tailwind.css styles named .card

2020-11-24 02:36 UTC, freedannyv commented on src/styles/tailwind.css
> +  @apply py-2 px-8 uppercase rounded-full shadow-lg bg-ff6350 text-base;
corrected